# Generated by Django 6.0.5 on 2026-05-11 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('date_range', models.CharField(max_length=50)),
                ('element', models.CharField(choices=[('fire', 'Fire'), ('earth', 'Earth'), ('air', 'Air'), ('water', 'Water')], max_length=10)),
                ('ruling_planet', models.CharField(max_length=50)),
                ('lucky_number', models.IntegerField()),
                ('lucky_color', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CosmicEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('eclipse', 'Eclipse'), ('full_moon', 'Full Moon'), ('new_moon', 'New Moon'), ('planetary_alignment', 'Planetary Alignment'), ('retrograde', 'Retrograde'), ('other', 'Other')], max_length=50)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('impact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_signs', models.ManyToManyField(related_name='cosmic_events', to='horoscopes.zodiacsign')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('horoscope_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('prediction', models.TextField()),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('lucky_numbers', models.CharField(max_length=100)),
                ('lucky_color', models.CharField(blank=True, max_length=50)),
                ('lucky_day', models.CharField(blank=True, max_length=50)),
                ('love', models.IntegerField(default=5)),
                ('money', models.IntegerField(default=5)),
                ('health', models.IntegerField(default=5)),
                ('career', models.IntegerField(default=5)),
                ('family', models.IntegerField(default=5)),
                ('advice', models.TextField(blank=True)),
                ('caution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zodiac_sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horoscopes', to='horoscopes.zodiacsign')),
            ],
            options={
                'ordering': ['-date', 'zodiac_sign'],
                'unique_together': {('zodiac_sign', 'date', 'horoscope_type')},
            },
        ),
    ]
